import { namesDataTypes } from "@/types/namesDataTypes";

  export const NamesData: namesDataTypes[] =[
  { name: 'Abubakar', gender: 'Male', prominentCity: 'Kano', meaning: 'Father of the young camel' },
  { name: 'Ahmadu', gender: 'Male', prominentCity: 'Sokoto', meaning: 'Praiseworthy' },
  { name: 'Aminu', gender: 'Male', prominentCity: 'Zaria', meaning: 'Faithful, trustworthy' },
  { name: 'Bashir', gender: 'Male', prominentCity: 'Maiduguri', meaning: 'Bringer of good news' },
  { name: 'Dauda', gender: 'Male', prominentCity: 'Katsina', meaning: 'Beloved' },
  { name: 'Farouk', gender: 'Male', prominentCity: 'Kaduna', meaning: 'One who distinguishes between right and wrong' },
  { name: 'Garba', gender: 'Male', prominentCity: 'Bauchi', meaning: 'Man of pride' },
  { name: 'Haruna', gender: 'Male', prominentCity: 'Gombe', meaning: 'Highborn' },
  { name: 'Idris', gender: 'Male', prominentCity: 'Yola', meaning: 'Studious, lord' },
  { name: 'Isma\'il', gender: 'Male', prominentCity: 'Sokoto', meaning: 'Heard by God' },
  { name: 'Kabiru', gender: 'Male', prominentCity: 'Kano', meaning: 'Great' },
  { name: 'Lamido', gender: 'Male', prominentCity: 'Yola', meaning: 'Chief' },
  { name: 'Mahmud', gender: 'Male', prominentCity: 'Kano', meaning: 'Praised, commendable' },
  { name: 'Musa', gender: 'Male', prominentCity: 'Sokoto', meaning: 'Saved from the waters' },
  { name: 'Sani', gender: 'Male', prominentCity: 'Katsina', meaning: 'Second son' },
  { name: 'Suleiman', gender: 'Male', prominentCity: 'Gombe', meaning: 'Peaceful' },
  { name: 'Umaru', gender: 'Male', prominentCity: 'Bauchi', meaning: 'Flourishing' },
  { name: 'Usman', gender: 'Male', prominentCity: 'Zaria', meaning: 'Baby bustard (a bird)' },
  { name: 'Yakubu', gender: 'Male', prominentCity: 'Kaduna', meaning: 'Supplanter' },
  { name: 'Yusuf', gender: 'Male', prominentCity: 'Maiduguri', meaning: 'God will add' },

  { name: 'Amina', gender: 'Female', prominentCity: 'Kano', meaning: 'Trustworthy, faithful' },
  { name: 'Asma\'u', gender: 'Female', prominentCity: 'Sokoto', meaning: 'Elevated, eminent' },
  { name: 'Fatima', gender: 'Female', prominentCity: 'Zaria', meaning: 'Captivating' },
  { name: 'Hadiza', gender: 'Female', prominentCity: 'Maiduguri', meaning: 'One who is born after twins' },
  { name: 'Halima', gender: 'Female', prominentCity: 'Katsina', meaning: 'Gentle, mild-mannered' },
  { name: 'Hauwa', gender: 'Female', prominentCity: 'Kaduna', meaning: 'Eve (first woman)' },
  { name: 'Jamila', gender: 'Female', prominentCity: 'Bauchi', meaning: 'Beautiful' },
  { name: 'Khadija', gender: 'Female', prominentCity: 'Gombe', meaning: 'Early baby, trustworthy' },
  { name: 'Lubna', gender: 'Female', prominentCity: 'Yola', meaning: 'Elegance' },
  { name: 'Maryam', gender: 'Female', prominentCity: 'Sokoto', meaning: 'Bitter, beloved' },
  { name: 'Nana', gender: 'Female', prominentCity: 'Kano', meaning: 'Grace' },
  { name: 'Safiya', gender: 'Female', prominentCity: 'Zaria', meaning: 'Pure' },
  { name: 'Zainab', gender: 'Female', prominentCity: 'Maiduguri', meaning: 'Father\'s adornment' },

  { name: 'Bilkisu', gender: 'Unisex', prominentCity: 'Kano', meaning: 'Queen' },
  { name: 'Habiba', gender: 'Unisex', prominentCity: 'Sokoto', meaning: 'Beloved, friend' },
  { name: 'Mubarak', gender: 'Unisex', prominentCity: 'Zaria', meaning: 'Blessed' },
  { name: 'Rahma', gender: 'Unisex', prominentCity: 'Maiduguri', meaning: 'Mercy, compassion' },
  { name: 'Salisu', gender: 'Unisex', prominentCity: 'Katsina', meaning: 'Secure, protected' },
];